spring.application.name=book-management


# DATABASE CONFIG
spring.datasource.driver-class-name = org.postgresql.Driver

spring.datasource.url = jdbc:postgresql://localhost:5432/books
spring.datasource.username = postgres
spring.datasource.password = postgres

spring.datasource.hikari.minimumIdle = 1
spring.datasource.hikari.maximumPoolSize = 5
spring.datasource.hikari.pool-size=30

spring.jpa.hibernate.ddl-auto = update


# SERVER CONFIG
server.port=8073
server.address=0.0.0.0